# Generated by binpac_quickstart

refine flow MySQL_Flow += {
	function proc_mysql_message(data: bytestring): bool
		%{
		BifEvent::generate_mysql_event(connection()->bro_analyzer(), connection()->bro_analyzer()->Conn());
		return true;
		%}
};

