// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "MYSQL.h"

BRO_PLUGIN_BEGIN(Bro, MYSQL)
	BRO_PLUGIN_DESCRIPTION("MySQL analyzer");
	BRO_PLUGIN_ANALYZER("MYSQL", MySQL::MYSQL_Analyzer);
	BRO_PLUGIN_BIF_FILE(events);
BRO_PLUGIN_END